ArchitetturaServiziBase = ["B£", "C£", "A£", "WF", "D9", "JA", "NS", "LO"]
GestioneAnagrafici = ["BR", "CF", "MT"]
AmministrazioneFinanzaControllo = ["C5", "A5", "D5", "D0"]
Vendite = ["V6", "RE"]
Pianificazione = ["MP", "M5", "JM"]
Produzione = ["P5", "S5"]
Acquisti = ["V4", "V5", "G9"]
Logistica = ["GM"]
QualitaManutenzione = ["CQ", "MM"]
OpenIntegration = ["PH", "ED", "WS", "NG", "OD"]
WebApplication = ["WE"]

areeApplicative = [ArchitetturaServiziBase, GestioneAnagrafici, AmministrazioneFinanzaControllo, Vendite, Pianificazione, Produzione, Acquisti, Logistica, QualitaManutenzione, OpenIntegration, WebApplication]

nomiAreeApplicative = ["Architettura e Servizi di Base", "Gestione Anagrafici", "Amministrazione Finanza Controllo", "Vendite", "Pianificazione", "Produzione", "Acquisti", "Logistica", "Qualita Manutenzione", "Open-Integration", "WebApplication"]

areeApp = {
    "000010" : nomiAreeApplicative[0],
    "000020" : nomiAreeApplicative[1],
    "000030" : nomiAreeApplicative[2],
    "000040" : nomiAreeApplicative[3],
    "000050" : nomiAreeApplicative[4],
    "000060" : nomiAreeApplicative[5],
    "000070" : nomiAreeApplicative[6],
    "000080" : nomiAreeApplicative[7],
    "000090" : nomiAreeApplicative[8],
    "000100" : nomiAreeApplicative[9],
    "000110" : nomiAreeApplicative[10]
}


applicazioni = {
    "B£" : "Funzioni Base",
    "C£" : "Dati di Classificazione",
    "A£" : "Funzioni Tecniche", 
    "WF" : "Workflow", 
    "D9" : "Business Intelligence", 
    "JA" : "Client-Server service", 
    "NS" : "Funzioni di Network", 
    "LO" : "Funzioni Ambiente Grafico",
    "BR" : "Dati di Base", 
    "CF" : "Configuratore", 
    "MT" : "Modifiche Tecniche",
    "C5" : "Contabilità Generale", 
    "A5" : "Cespiti", 
    "D5" : "Contabilità Industriale", 
    "D0" : "Costi Avanzati",
    "V6" : "Vendite", 
    "RE" : "CRM Relazioni Cliente",
    "MP" : "MPS Piano Princ. Produzione", 
    "M5" : "MRP Pianific. Materiali", 
    "JM" : "Analisi Mat. Per Commesse",
    "P5" : "Produzione", 
    "S5" : "Schedulaz. Capacità Finita", 
    "V4" : "Richieste Di Acquisto", 
    "V5" : "Acquisti", 
    "G9" : "Post Acquisto", 
    "GM" : "Magazzino", 
    "CQ" : "Qualità", 
    "MM" : "Manutenzioni", 
    "PH" : "Gestione Dati di Campo", 
    "ED" : "EDI Elett.Data Interchange", 
    "WS" : "Integrazione CMS", 
    "NG" : "Negoziando", 
    "OD" : "Documentale", 
    "WE" : "Componenti Web"
}

moduli = {
    "A5BASE" : "Funzioni comuni",
    "A5CAMO" : "Calcolo e movimenti",
    "A5OPCO" : "Operazioni contabili",
    "AAV_01" : "Produzione a commessa",
    "A£BASE" : "Standard Tecnici",
    "A£DEMO" : "Esempi&#x2f;Dimostrabilità",
    "A£FORM" : "Formazione Sme.up",
    "A£LABS" : "Laboratorio",
    "A£LING" : "Supporto multilingua",
    "A£MOPE" : "Monitor e performance",
    "A£NEWS" : "News Sme.up",
    "A£PLUG" : "TTR Time to Run",
    "A£SHCI" : "L'approccio Sme.UP alla Human Computer Interaction",
    "A£SYST" : "Know how sistemistico",
    "A£WORK" : "Test Gestione Archivi",
    "A£_000" : "Sketch",
    "A£_001" : "UPP - Definizione",
    "A£_079" : "Showcase",
    "A£_094" : "Info strutturate UPP",
    "A£_103" : "Gestione dei Branch",
    "BRARES" : "Dati Ente&#x2f;Articolo",
    "BRARTI" : "Articoli",
    "BRCAMB" : "Cambi Valutari",
    "BRCATA" : "Catalogo",
    "BRCICL" : "Cicli",
    "BRCOMM" : "Commesse",
    "BRCONF" : "Configurazione",
    "BRDINT" : "Dichiarazione d'intento",
    "BRDIST" : "Distinta Base",
    "BRENTI" : "Enti",
    "BRIPDM" : "Integrazione PDM",
    "BRRIPS" : "Funzioni di una fase e Risorse prod.secondarie",
    "BR_069" : "Integrazione S-Peek",
    "B£AMBI" : "Ambienti Sme.up",
    "B£AUTO" : "Autorizzazioni",
    "B£BASE" : "Funzioni comuni",
    "B£BCDO" : "Script BCD",
    "B£CALE" : "Calendario",
    "B£CARR" : "Carrello",
    "B£CONV" : "Conversioni",
    "B£DOCU" : "Documentazione Sme.up",
    "B£EQRY" : "Documentazione Query",
    "B£FIND" : "Motore di ricerca SME.up - Cerca",
    "B£FLUS" : "Flussi di funzioni",
    "B£GOGG" : "Gestione Oggetti Smeup",
    "B£GPTF" : "PTF di Sme.up",
    "B£INTE" : "Controllo interfacce",
    "B£LISD" : "Liste di distribuzione",
    "B£LIST" : "Liste di Oggetti di Oggetti",
    "B£LOGG" : "Log in Sme.up",
    "B£MATE" : "Holt Winters",
    "B£MENU" : "Menù Sme.up",
    "B£MUTE" : "Memorizzazioni Utente",
    "B£NOTE" : "Note",
    "B£OGAT" : "Frame&#x2f;Slot oggetti&#x2f;Attributi",
    "B£STAM" : "Stampe",
    "B£TABE" : "Tabelle parametriche",
    "B£UTIL" : "Utility",
    "B£WKFL" : "Stati",
    "B£WSME" : "Work with Sme.up",
    "B£WSYS" : "Work with system",
    "B£_050" : "BELLINI QUINTO",
    "B£_072" : "Gestione Taglie-Colori",
    "B£_105" : "Servizio di stampa RDS",
    "C5BASE" : "Funzioni comuni",
    "C5C010" : "Contabilità Generale",
    "C5C020" : "Contabilità Iva",
    "C5C040" : "Controllo Documenti&#x2f;Fatture",
    "C5C070" : "Ritenute d'acconto",
    "C5C090" : "Intrastat",
    "C5C100" : "Comunicazioni Valutarie Statistiche",
    "C5COAP" : "Concetti Applicativi di Base",
    "C5COTE" : "Concetti tecnici di base",
    "C5D010" : "Incassi e Pagamenti",
    "C5D020" : "Solleciti",
    "C5D030" : "Tesoreria",
    "C5D050" : "Disponibilità Finanziaria",
    "C5DIZI" : "Dizionario termini contabilità",
    "C5E010" : "Bilancio",
    "C5E020" : "Contabilità Gestionale",
    "C5E030" : "Contabilità Analitica",
    "C5E040" : "Consolidato",
    "C5E060" : "Cruscotti Direzionali e Indicator-Documentazione",
    "C5LOOC" : "Sviluppi Looc.up",
    "C5_093" : "Registrazione Fatture Elettroniche",
    "C5_101" : "Gestione divisione",
    "C5_104" : "Gestione divisione",
    "CFBASE" : "Configuratore",
    "CQACMC" : "Strumenti di misura",
    "CQAUDT" : "Audit",
    "CQAVVI" : "Avviamento Veloce",
    "CQBASE" : "Funzioni comuni",
    "CQCCO2" : "Cicli di collaudo estesi",
    "CQCCOL" : "Cicli di collaudo",
    "CQDOCU" : "SVI Gestione e Contr. Documentazione",
    "CQEART" : "Dati Ente Articolo",
    "CQFMEA" : "F.M.E.A.",
    "CQLOTT" : "Lotti",
    "CQMATR" : "Matrice delle responsabilità",
    "CQNCNF" : "Non conformità",
    "CQNCOG" : "Non Conformità per oggetto",
    "CQPARE" : "Analisi non conformità",
    "CQPDCA" : "Piani di Campionamento",
    "CQPERS" : "Addestramento",
    "CQRDI2" : "Richieste Intervento    Ver.WF",
    "CQRDIN" : "Richieste d'Intervento",
    "CQRICO" : "Rilievi e collaudi",
    "CQVEND" : "Analisi fornitore",
    "CQ_007" : "TODO",
    "CQ_108" : "PPAP",
    "C£ALIA" : "Alias",
    "C£BASE" : "Funzioni comuni",
    "C£ESMO" : "Esponenti di modifica",
    "C£LEGA" : "Legami",
    "C£LIST" : "Listini",
    "C£MODI" : "Modello dinamico",
    "C£PARA" : "Parametri",
    "C£SINT" : "Sintesi degli oggetti",
    "D0BASE" : "Funzioni comuni",
    "D0CALC" : "Calcolo costi",
    "D0CCMC" : "Calcolo costi Oggetto",
    "D0_086" : "Analisi&#x2f;confronto costi distinte",
    "D5BASE" : "Delt.up - Funzioni base",
    "D5GKPI" : "KPI",
    "D5NUOG" : "Modulo D5NUOG",
    "D9BASE" : "Funzioni base",
    "D9QLIK" : "QLik",
    "EDBASE" : "Modulo Base",
    "EDMAIL" : "Mail.up",
    "G9BASE" : "PURC_up Post-purchase",
    "GABASE" : "Foto e Analisi inventari",
    "GMANIN" : "Foto e Analisi inventari",
    "GMBASE" : "Ware_UP Funzioni comuni",
    "GMCOLL" : "Colli",
    "GMFISC" : "Attività fiscali",
    "GMGIAC" : "Giacenze",
    "GMINVE" : "Inventario fisico",
    "GMMOVI" : "Movimenti",
    "GMRIMO" : "Richieste di movimentazione",
    "GMRINT" : "Rintracciabilità",
    "GMUBIC" : "Ubicazioni",
    "IGREPT" : "Indici &#x2f; report",
    "JALOGT" : "Log collegamenti Looc.up e Web.up",
    "JATESI" : "Verifica risorse",
    "LOBASE" : "Documentazione applicazione",
    "LOCA02" : "Analisi di tempo",
    "LOCA07" : "Raccoglitore di funzioni",
    "LOCACC" : "Accordion",
    "LOCACT" : "Azioni virtuali",
    "LOCATM" : "ATM - Activity timeline",
    "LOCBAS" : "Indice componente BASE",
    "LOCBOX" : "Documentazione del componente BOX",
    "LOCBTN" : "Bottone",
    "LOCCAL" : "CAL - Calendario",
    "LOCCAM" : "Documentazione camera",
    "LOCCDE" : "",
    "LOCCND" : "Componente CountDown",
    "LOCCOM" : "Componente Comunicazione",
    "LOCCOS" : "Costruttori",
    "LOCCUB" : "Componente Cubo Indice",
    "LOCDBM" : "Componente Database Migration",
    "LOCDSH" : "Componente Dash",
    "LOCDYN" : "Componente dinamico",
    "LOCEDT" : "",
    "LOCEML" : "Documentazione componente EML",
    "LOCEMU" : "Componente Emulatore",
    "LOCEVT" : "Componente Eventi Multipli",
    "LOCEXA" : "EXA - Grafici",
    "LOCEXB" : "Componente Matrice",
    "LOCEXC" : "Foglio Elettronico",
    "LOCEXD" : "Documentazione componente scheda",
    "LOCEXU" : "Matrice di aggiornamento",
    "LOCFBK" : "Componente FBK",
    "LOCFLD" : "FLD - Field",
    "LOCFLU" : "Componente Flusso Azioni",
    "LOCFRM" : "Costruzione output PDF",
    "LOCFRX" : "TST",
    "LOCG30" : "Componente Questionario",
    "LOCG53" : "Stampa in PDF",
    "LOCGAU" : "Gauge",
    "LOCGEO" : "Geolocalizzazione",
    "LOCGND" : "GND - Gantt dinamico",
    "LOCGNT" : "GNT - Gantt schedulatore",
    "LOCGRP" : "Componente Grafo",
    "LOCHTM" : "Documentazione componente HTM",
    "LOCHTR" : "Documentazione albero orizzontale",
    "LOCIFL" : "Componente IFL",
    "LOCIMD" : "Gestore immagini dinamiche",
    "LOCIMG" : "Immagine",
    "LOCIML" : "Lista immagini",
    "LOCINP" : "Componente Input Panel",
    "LOCINT" : "Servizi interni",
    "LOCJSO" : "JSON",
    "LOCKNO" : "Componente Knob",
    "LOCLAB" : "Label",
    "LOCLIN" : "Componente Line",
    "LOCMAP" : "Componente Immagine attiva",
    "LOCMIN" : "",
    "LOCMSG" : "Documentazione componente messaggi",
    "LOCMSS" : "Componente messaggio",
    "LOCOGN" : "Organigramma",
    "LOCONV" : "Istruzioni per compilare",
    "LOCOPN" : "Documentazione del componente OPN",
    "LOCOUT" : "Documentazione Output Panel",
    "LOCPAT" : "PAT - Path",
    "LOCPAY" : "",
    "LOCPDF" : "PDF Reader",
    "LOCPGB" : "",
    "LOCREP" : "Componente Report",
    "LOCSEM" : "Documentazione semaforo",
    "LOCSET" : "Setup",
    "LOCSHE" : "",
    "LOCSPC" : "Statistical Process Control",
    "LOCSPL" : "Componente Spotlight",
    "LOCSRI" : "Ingressi da seirale",
    "LOCSYS" : "F.A.Q. LOCSYS",
    "LOCTCL" : "Componente Tag Cloud",
    "LOCTED" : "",
    "LOCTML" : "TML - Timeline",
    "LOCTMP" : "TMP - Treemap",
    "LOCTRA" : "",
    "LOCTRE" : "Componente Albero",
    "LOCTXT" : "Documentazione componente TXT",
    "LOCWFD" : "Workflow designer",
    "LOFILE" : "Modulo dei file di Looc.UP",
    "LOGATW" : "Sme.UP Gateway",
    "LOSMEG" : "Sme.UP GO e Updater lato client",
    "LOSSON" : "SSO - Single Sign On",
    "LOSUIR" : "Standard User Input Requests",
    "LO_080" : "Sme.UP Gateway - console gestione",
    "M5ATPR" : "A.T.P.",
    "M5BASE" : "Marp.up - Material Requirements Plng",
    "M5CMRP" : "Marp.up - Pianificazione",
    "M5DISP" : "Marp.up - Disponibilità",
    "M5PLUG" : "Avviamento veloce dell'MRP",
    "M5_005" : "Multiplant",
    "M5_006" : "MRP&#x3a; Gradi di libertà",
    "M5_007" : "MRP&#x3a; Parametri di pianificazione per riferimento",
    "M5_008" : "MRP&#x3a; OAV di articoli e parametri di pianificazione",
    "M5_012" : "MRP a Capacità Finita",
    "M5_013" : "MRP Logistico",
    "M5_014" : "Criterio Make or Change",
    "M5_015" : "Scorta minima",
    "M5_016" : "HM",
    "M5_017" : "Punto di riordino",
    "M5_018" : "Assegna fornitore-contratto a suggerimenti",
    "M5_019" : "SELFIE MRP",
    "M5_020" : "DRP leggero",
    "M5_021" : "MRP Rottura di Esponente Modifica",
    "MMBASE" : "Mant.up   Base",
    "MMSINT" : "Mant.up   Interventi",
    "MMTEST" : "Mant.up   Macchine",
    "MM_PIA" : "Pianificazione Introduzione Manutenzione",
    "MOBASE" : "Applicazione mobile Sme.app",
    "MOOFFL" : "La gestione dati offline",
    "MPBDGT" : "Budget",
    "MPHW02" : "Holt Winters&#x3a; avviamento veloce",
    "MPHW03" : "HW Popolamento dati per demo",
    "MPHW04" : "Gestione secondo oggetto di rottura",
    "MPPIAN" : "MPS",
    "MPP_01" : "MPS",
    "MUBASE" : "Base Multipiattaforma",
    "MUCONV" : "Conversione",
    "MUDBMS" : "Database",
    "MUDEVK" : "Sviluppo",
    "MUHOST" : "Sistema Ospitante",
    "MULANG" : "Linguaggio",
    "MULOOC" : "Integrazioni Looc.UP",
    "MUMACH" : "Machine Interface",
    "MUNETC" : "Communication",
    "MUOPER" : "Sistema",
    "MURUNT" : "Runtime",
    "MUTEST" : "Test",
    "NSBASE" : "Servizi di comunicazione",
    "NSPRNT" : "Servizi di stampa",
    "NSSKIT" : "Documentazione Smartkit",
    "NS_099" : "Smartkit management",
    "ODBASE" : "Cosa intendiamo per documentale",
    "ODCAPT" : "Modulo capture",
    "ODIAAB" : "Interfaccia Archiviazione Archibox",
    "ODIACM" : "Interfaccia documentale Content Manager",
    "ODIACO" : "Interfaccia documentale Comped",
    "ODIAED" : "Interfaccia documentale EDOK",
    "ODIAME" : "Interfaccia Archiviazione Medusa",
    "ODMAIL" : "Interfaccia IMAP",
    "ODMFUN" : "Multifunzione",
    "OD_098" : "Google Drive Integration",
    "P0DPPS" : "Documento Programmatico Per la Sicurezza",
    "P0_077" : "Gestione Corsi Formazione",
    "P5BASE" : "Dati di base",
    "P5IMPE" : "Impegni materiali",
    "P5ORDI" : "Prod.UP Ordini produzione",
    "P5PADC" : "Produzione a disponibilità chiamata",
    "P5PLUG" : "Attivazione",
    "P5PMFP" : "Produzione MFP",
    "PHBASE" : "Informazioni base PH",
    "PHDEMO" : "Documentazione PHDEMO",
    "PHIIOT" : "Documentazione PHIIOT",
    "PHIMES" : "Modulo MES",
    "PHRETE" : "Componenti PH",
    "PH_030" : "Pareto Macchine",
    "PH_037" : "Timeline Macchine MES",
    "PH_038" : "Lista Macchine MES",
    "PH_048" : "Analisi KPI&#x2f;rese",
    "PH_049" : "Cruscotto MES della macchina",
    "PH_060" : "Azioni configurabili MES",
    "REACCA" : "Anagrafici",
    "REBASE" : "Funzioni di base",
    "REEBSN" : "E-Business",
    "REGESA" : "Anagrafici",
    "RELEAD" : "Lead",
    "REMAMA" : "Mail marketing",
    "REMARK" : "Marketing e Prevendita",
    "REOPPO" : "Opportunità",
    "REPOSV" : "Servizi post-vendita",
    "REREFE" : "Anagrafici",
    "REREPO" : "Reports &#x26; Dashboards",
    "RETELE" : "Documentazione appl.RE modulo TELE",
    "REVEND" : "Vendite",
    "REWEBM" : "Web &#x26; Mobile",
    "RE_008" : "Gestione esportazione VCF&#x2f;ICS",
    "RE_035" : "",
    "S5GPRO" : "Gestione Progetti BCD",
    "S5IRIS" : "Documentazione Applicativa",
    "S5_001" : "Schedulazione a Capacità Infinita",
    "S5_002" : "Schema schedulazione capacità infinita",
    "T5CONS" : "Payr.up - Consolle del personale",
    "V5BASE" : "Funzioni comuni",
    "V5DOCU" : "Gestione documenti",
    "V5FATT" : "Fatturazione",
    "V5FTPA" : "Fattura elettronica",
    "V5LIST" : "Gestione Listini",
    "V5PLUG" : "Avviamento veloce di Trad.up",
    "V5PROV" : "Provvigioni",
    "V5RIDA" : "Richieste di acquisto - SV",
    "V5SPRI" : "Azioni spedizioni &#x2f; ricevimenti",
    "V5STAT" : "Modulo V5STAT",
    "V5TRIP" : "Viaggi",
    "V5_002" : "Impostazione Conto Lavoro Attivo",
    "V5_021" : "Gestione righe documenti",
    "WEBASE" : "Web.up - Internet Components",
    "WETEST" : "Aspetti generali",
    "WEVUEJ" : "Componenti web",
    "WFBASE" : "Workflow - modulo base",
    "WSBASE" : "Visione Show.Up",
    "WSREOB" : "Oggetti remoti",
    "WS_001" : "Note tecniche"
}

nomiDOC_SCH = {
    "A5OPCO" : "Scheda Controllo Quadratura Cespiti - Co.Ge",
    "A5OPCO_CO0" : "Scheda Associazione Conti per Categoria",
    "A5OPCO_CO1" : "Scheda collegamento Cespiti - Co.Ge generiche",
    "A5OPCO_CO2" : "Scheda collegamento Cespiti - Co.Ge per categoria",
    "A5OPCO_CO3" : "Scheda collegamento Cespiti - Co.Ge per cespite",
    "A5_056" : "Albero Componenti Cespiti",
    "A5_056_01" : "Albero Componenti Cespiti - Componenti -",
    "A5_056_02" : "Albero Componenti Cespiti - Movimenti  -",
    "A5_064" : "Quadratura componenti cespiti",
    "A£_000" : "Sketch",
    "A£_079" : "UPP di navigazione",
    "BRCICL_OGA" : "Navigazione cicli di lavoro",
    "BRDINT_17" : "",
    "BR_069" : "Integrazione S-Peek",
    "B£AUTO" : "Scheda Autorizzazioni applicative",
    "B£AUTOES" : "Autorizzazioni",
    "B£DOCU_F1" : "Help",
    "B£DOCU_FI" : "Gestione delle Figure",
    "B£EQRY_SEA" : "Documentazione Query",
    "B£EQRY_ST" : "Scheda Test Scheda B£EQRY_SEA",
    "B£FIND" : "Motore di ricerca SME.up - Cerca",
    "B£SER_33" : "Funzioni su Calendari",
    "B£SER_89" : "Controllo Errori",
    "C5C020_LIQ" : "Scheda Liquidazione IVA",
    "C5D010_PAR" : "Scheda Controllo Pareggi",
    "C5D030_AFF" : "Scheda Controllo Affidamenti",
    "C5D030_ANA" : "Scheda Anagrafica Rapporti Bancari",
    "C5D030_ANT" : "Scheda Controllo Anticipi",
    "C5D030_COP" : "Scheda Condizioni per Rapporto&#x2f;Operazione",
    "C5D030_CRU" : "Scheda Controllo Registrazioni Automatiche",
    "C5D030_FII" : "Scheda Gestione Fideiussioni",
    "C5D030_RIM" : "Scheda Spunta Manuale",
    "C5D030_UTB" : "Scheda Aggiornamento Tassi Interbancari",
    "C5E010BDIV" : "Bilancio per divisione",
    "C5E010BPER" : "Analisi di un Periodo",
    "C5E010_COM" : "Controllo Ratei&#x2f;Risconti",
    "C5E010_RIS" : "Controllo Risconti Aperti",
    "C5E030_STR" : "Analisi struttura Analitica",
    "C5ESER_28" : "Bilancio per divisione",
    "C5SER25T" : "Scheda Analisi Partite - Totali",
    "C5SER_21" : "Scadenzario",
    "C5SER_25" : "Partitario",
    "C5SER_27" : "Scheda proiezione saldi banca",
    "C5SER_32" : "Interrogazioni Saldi Tesoreria",
    "C5SER_39A" : "Pagamenti del Periodo",
    "C5SER_40" : "Scheda Analisi Incassi&#x2f;Pagamenti",
    "C5SER_54" : "Scheda Controllo Generale &#x2f; IVA",
    "C5SER_59" : "Conti a Partite",
    "C5_003" : "Rendiconto Finanziario",
    "CMP_EXDA" : "Scheda EXD - Drag &#x26; Drop",
    "CMP_EXU" : "Scheda CMP_EXU",
    "CMP_EXUA" : "Scheda CEXU - Aggiornamento MonoLine",
    "CMP_EXUB" : "CEXU - Aggiornamento MultiLine",
    "CMP_INPMOD" : "Scheda Esempio CMP_INP - MOD",
    "CMP_INP_D" : "Scheda Esempio CMP_INP_D",
    "CNAZI" : "Scheda Azienda",
    "CNAZI_DP" : "Scheda Azienda_DPS",
    "CNCLI" : "Cliente",
    "CN_D" : "Gestione Contatti",
    "CN_DDIF" : "Gestione Contatti - Allineamento Differenze",
    "CN_RNOM" : "Ricerca Nominativi",
    "COS_A08" : "Esempi su Utilizzo LOA08",
    "C£LIST" : "Scheda Listini",
    "D0DOCU" : "Scheda documentazione calcolo costi",
    "D0ERRO" : "Scheda errori calcolo costi",
    "D0MENU" : "Scheda Menù Nuova Gestione Costi",
    "D5COSO_Q" : "Scheda D5COSO_QRY",
    "D5VWIP" : "Scheda Valorizzazione WIP",
    "D9BASE" : "Scheda Funzioni di base business intelligence",
    "ESE1D" : "Scheda esempio layout dinamico",
    "ESE1I" : "Script di esempio - aggiornamento in matrice",
    "F2" : "Scheda WFBASE",
    "F2_EXEC" : "Scheda esecuzione di un impegno",
    "F2_EXT" : "Scheda gestione sottoimpegni extra-rete",
    "GMANIN" : "Scheda Foto e Analisi Inventari",
    "HELP" : "Scheda Help contestuale",
    "J1PATHD" : "Scheda gestione path&#x2f;directory",
    "J1PATHDIRX" : "Scheda Gestione semplificata directory",
    "J1PATHDX" : "Scheda Gestione semplificata directory-VERIFICARE",
    "J1STR_CRU" : "Analisi di una stringa",
    "J8" : "Scheda Directory Remota",
    "J9" : "Scheda File Remoto",
    "LI" : "Scheda Funzioni su Liste",
    "LOA02" : "Scheda analisi di due valori nel tempo",
    "LOA03" : "Scheda analisi di due oggetti con valori",
    "LOA15" : "Scheda analisi delle fonti",
    "LOCG30_H" : "Scheda Help Wizard Script",
    "LOCTRE_S" : "Scheda Selezione Tag Wizard",
    "LOSUIR_A" : "LOSUIR - Esempi su Utilizzo Sezioni&#x2f;Finestre",
    "LOSUIR_B" : "LOSUIR - Esempi su Utilizzo Setup e Dinamismi",
    "LOSUIR_C" : "LOSUIR - Esempi su Utilizzo Memorizzazioni",
    "LOSUIR_D" : "LOSUIR - Esempi su Messaggi di Conferma",
    "LOSUIR_E" : "LOSUIR - Esempi su Utilizzo Configurazioni",
    "LOSUIR_F" : "LOSUIR - Esempi su Utilizzo Richieste Parametri",
    "LOSUIR_G" : "LOSUIR - Esempi su Utilizzo Query",
    "LO_080" : "Sme.UP Gateway - console gestione",
    "M5" : "Suggerimento pianificazione",
    "M5CMRP" : "Pianificazione - Base",
    "M5CMRP_A" : "Scheda Pianif. Quantità superflua",
    "M5CMRP_I" : "Scheda Pianif. Indici",
    "M5CMRP_N" : "Scheda Pianif. Navigazione",
    "M5CMRP_TGA" : "Scheda Analisi nel tempo per gruppo",
    "M5CMRP_TPA" : "Scheda Analisi nel tempo per periodo",
    "MBSCP_SCH" : "Scheda",
    "MPPIAN" : "Navigazione MPS",
    "MPPIANGR" : "Scheda Rappresentazione grafica dati MPS",
    "MPPIAN_FAM" : "Navigazione MPS per Famiglia",
    "MPPIAN_GRA" : "Grafici MPS",
    "MPPIAN_OGG" : "Navigazione MPS  per Oggetto",
    "MPPIAN_PIA" : "Navigazione MPS  per Piano",
    "MPPIAN_RVP" : "Scheda MPS Riga di una vista piano",
    "MPPIAN_TKY" : "Navigazione MPS  per Tipo chiavi",
    "MPPIAN_VDP" : "Scheda MPS Visualizzazione Vista Piano",
    "MPPIAN_VIS" : "Navigazione MPS  per Vista",
    "MSG" : "Gruppo Messaggi Loocup",
    "OGBASE_CLP" : "Gestione Incolla - Clipboard",
    "OGBASE_ICO" : "",
    "OGBASE_IMG" : "Gestione immagine oggetto",
    "OGBASE_NOT" : "Gestione note",
    "OJFILE" : "Scheda Tracciato file",
    "OJFILE_B" : "Scheda B Analisi tabellare file",
    "OJFILE_C" : "Scheda C Dettaglio file",
    "OJFILE_D" : "Scheda D Aumento dimensione file",
    "OJFILE_E" : "Scheda E Analisi nel tempo file",
    "OJFILE_G" : "Scheda G Documentazione generale file",
    "OJFILE_K" : "Scheda K Cruscotto file",
    "OJFILE_L" : "Scheda L Logici di un file",
    "OJFILE_N" : "Scheda N Navigazione nel file",
    "OJFILE_O" : "Scheda O Oggetti Sme.UP nel file",
    "OJFILE_P" : "Scheda P Pareto per campo file",
    "OJFILE_R" : "Scheda R Riorganizzazione file",
    "OJFILE_S" : "Scheda S Sintesi file",
    "OJFILE_T" : "Scheda T Tracciato file",
    "OJ_FILE" : "Scheda Tracciato file",
    "OJ_USRPRF" : "Scheda Utente",
    "PH_012" : "Ambiente",
    "PH_018" : "Accessi",
    "PH_037" : "Timeline Macchine",
    "PH_043" : "Cruscotto Colpi",
    "PH_048" : "Analisi rese&#x2f;performance MES",
    "PH_049" : "Cruscotto Macchina",
    "Q3" : "Scheda oggetto filtro Q3",
    "S5BASE" : "Schedulazione grafica BCD",
    "SMSG" : "Scheda Singolo messaggio",
    "ST" : "Scheda Sett. Tabella",
    "ST_CC" : "Scheda Sett. Tabella Controllo contenuto",
    "ST_CO" : "Scheda Sett. Tabelle Contenuto tabelle",
    "ST_FT" : "Scheda Comparazione tabelle",
    "T5COS" : "Costo",
    "TAB£A" : "Scheda applicazione TAB£A",
    "UP" : "Scheda Utente",
    "V5PROV_CAN" : "Conguagli anticipi manuale",
    "V5PROV_CON" : "Controllo Stato Contabilizzazione P",
    "V5PROV_DEN" : "Distinta Enasarco",
    "V5PROV_REG" : "Controllo Ripresa Dati Coge",
    "V5STAT" : "Statistiche di fatturazione",
    "V5STAT_02" : "Scheda Report preparati",
    "V5STAT_03" : "Scheda Analisi di pareto",
    "V5STAT_10" : "Scheda Controlli Globali",
    "V5_021" : "Gestione righe documenti",
    "V5_082" : "Controllo esito fatturazione elettronica",
    "WFLSTWRK" : "Worklist",
    "WFU001" : "Utilità&#x3a; note domanda&#x2f;risposta su F2",
    "WFU002" : "Utilità&#x3a; note domanda&#x2f;risposta su F1",
    "£RICH01B" : "Utilità&#x3a; note domanda&#x2f;risposta + carrello"
}

moduliDOC_OPE = {
    "A5OPCO" : "Modulo Base",
    "A£FORM" : "Formazione Sme.up",
    "A£_000" : "Sketch",
    "BRARTI" : "Articoli",
    "BRCAMB" : "Cambi",
    "BRCICL" : "Cicli",
    "BRCOMM" : "Commesse",
    "BRDINT" : "Dichiarazioni d&#x27;intento",
    "BRDIST" : "Distinta",
    "BRENTI" : "Enti",
    "BRMATR" : "Matricole",
    "BRRISO" : "Risorse",
    "B£AUTO" : "Autorizzazioni applicative",
    "B£BASE" : "Funzioni comuni",
    "B£CALE" : "Calendario",
    "B£DOCU" : "Documentazione",
    "B£MENU" : "Menù Sme.UP",
    "B£MUTE" : "Memorizzazioni",
    "B£NOTE" : "Note Strutturate",
    "B£TABE" : "Tabelle",
    "B£UTIL" : "Utility",
    "B£_COM" : "Comandi Funzionali",
    "B£_LIS" : "Liste oggetti",
    "B£_OAV" : "Attributi di un oggetto",
    "B£_PAR" : "Parzializzazioni",
    "B£_RIC" : "Ricerche",
    "B£_SCH" : "Schemi di visualizzazione e stampa",
    "B£_STA" : "Stampe",
    "B£_VID" : "Formati video",
    "C5BASE" : "Modulo Base",
    "C5C010" : "Contabilità Generale",
    "C5C020" : "Contabilità IVA",
    "C5C040" : "Controllo Documenti&#x2f;Fatture",
    "C5C070" : "Ritenute d&#x27;Acconto",
    "C5C090" : "Intrastat",
    "C5C100" : "Comunicazioni Valutarie Statistiche",
    "C5D010" : "Incassi e Pagamenti",
    "C5D020" : "Solleciti",
    "C5D030" : "Tesoreria",
    "C5D050" : "Disponibilità Finanziaria",
    "C5E010" : "Bilancio",
    "C5E020" : "Contabilità Gestionale",
    "C5E030" : "Contabilità Analitica",
    "C5E040" : "Bilancio Consolidato",
    "CQAUDT" : "Audit",
    "CQCCOL" : "Ciclo di collaudo",
    "CQDOCU" : "Documentazione",
    "CQEART" : "Dati Ente&#x2f;Articolo",
    "CQFMEA" : "FMEA",
    "CQLOTT" : "Lotti",
    "CQNCNF" : "Non Conformità",
    "CQPARE" : "Analisi Non Conformità",
    "CQPDCA" : "Piani di Campionamento",
    "CQPERS" : "Addestramento",
    "CQRDI2" : "Richieste Intervento ver.2",
    "CQRDIN" : "Richieste d&#x27;intervento",
    "CQRICO" : "Rilievi e collaudi",
    "CQVEND" : "Rating",
    "C£ALIA" : "Alias",
    "C£DESC" : "Descrizioni estese",
    "C£ESMO" : "Esponenti di modifica",
    "C£LEGA" : "Legami",
    "C£LIST" : "Listini",
    "C£PARA" : "Parametri",
    "D0BASE" : "Calcolo costi",
    "D5VWIP" : "Valorizzazione WIP",
    "D9QLIK" : "QlikView documento Operativo",
    "EDMAIL" : "MailUP&#x3a; funzioni base",
    "G9BASE" : "Purc.up - Post Acquisto",
    "GMANIN" : "Analisi Inventari",
    "GMBASE" : "Funzioni Comuni",
    "GMCOLL" : "Colli - Contenitori",
    "GMFISC" : "Attività fiscali",
    "GMGIAC" : "Giacenze",
    "GMINVE" : "Inventario fisico",
    "GMMOVI" : "Movimenti",
    "GMRIMO" : "Richieste di Movimentazione",
    "GMRINT" : "Rintracciabilità",
    "GMUBIC" : "Ubicazioni",
    "IGREPT" : "Indici &#x2f; report",
    "LOBASE" : "Funzioni di base",
    "LOCACC" : "Menù azioni",
    "LOCALS" : "Gli alias",
    "LOCBAS" : "Modulo base",
    "LOCBTN" : "Bottoniera",
    "LOCDED" : "Drag and Drop",
    "LOCDEV" : "Interazione con device esterni",
    "LOCEDT" : "Text editor",
    "LOCEMU" : "Emulazione 5250",
    "LOCEXA" : "Grafico",
    "LOCEXB" : "Matrice",
    "LOCEXD" : "Scheda",
    "LOCG30" : "Questionario",
    "LOCGNT" : "Gantt",
    "LOCINP" : "Input panel",
    "LOCOGG" : "Ricerca di un oggetto",
    "LOCPOP" : "Popup",
    "LOCPRE" : "Gestione Preferiti",
    "LOCPRN" : "Stampe",
    "LOCSET" : "Setup",
    "LOCTAS" : "Comandi Rapidi",
    "LOCTIP" : "Campo tipizzato",
    "LOCTRE" : "Albero",
    "LOCWFD" : "Workflow designer",
    "LORRES" : "Cartelle",
    "LOSERV" : "Servizi",
    "LOSSON" : "SSO - Single Sign On",
    "M5BASE" : "Dati di base",
    "M5CMRP" : "Pianificazione",
    "M5DISP" : "Disponibilità",
    "MPBASE" : "Funzioni comuni",
    "MPCALE" : "Calendario",
    "MPPIAN" : "Piani",
    "MP_OPE" : "Generalità MPS",
    "NGBASE" : "Funzioni di base",
    "P5AVPR" : "Avanzamento Produzione",
    "P5BASE" : "Dati di base",
    "P5EVEN" : "Eventi",
    "P5IMPE" : "Impegni",
    "P5ORDI" : "Ordini di produzione",
    "P5PADC" : "Prod. Disponibilità Chiamata",
    "PH_037" : "Timeline Macchine",
    "S5IRIS" : "Schedulazione a capacità finita",
    "TPBASE" : "TWIN PULSE",
    "V5DOCU" : "Gestione documenti",
    "V5FATT" : "Fatturazione",
    "V5LIST" : "Listini",
    "V5PROV" : "Provvigioni",
    "V5SPRI" : "Spedizioni ricevimenti",
    "V5STAT" : "Statistiche sul fatturato",
    "WEBASE" : ""
}